### ISSUE TITLE
No 1.17 support

### ISSUE THREAD

**Issue by envizar** [pgmann/TabListHide#1]
The plugin does not work at all on version 1.17, the core is airplane. Writes the message "this is a bug, please report it please". Occurs when writing the /tlh hide command.

**Comment by Minionguyjpro** [comment]
This repo is outdated.

**Comment by Minionguyjpro** [comment]
theres no commits since 2017

**Comment by Minionguyjpro** [comment]
i forked it

**Comment by Minionguyjpro** [comment]
You can help me if you want

**Comment by pgmann** [comment]
Hi, yes I'm afraid this hasn't been updated since I first made it and as such likely won't work with newer versions unless I'm inspired to fix it. 

The main reason for this is that removing names from the tab list can cause bugs which are difficult to solve, for example I remember one where the hidden player would not be visible to players in the game world after they'd went out of render distance - so I'd need to find a fix for that if I update this.

I may update if I get time in the future as it was a fun plugin to work on, but time is currently quite limited.

**Comment by Minionguyjpro** [comment]
OK
